<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-CJECPP6" failures="1" tests="1" name="Registration" time="10.172" errors="0" timestamp="2023-11-05T14:04:06 CET">
  <testcase classname="com.parabank.tests.RegistrationTest" name="register" time="2.173">
    <failure type="java.lang.AssertionError" message="Registration Successful expected [Your account was created successfully. You are now logged in.] but found [An internal error has occurred and has been logged.]">
      <![CDATA[java.lang.AssertionError: Registration Successful expected [Your account was created successfully. You are now logged in.] but found [An internal error has occurred and has been logged.]
at com.parabank.tests.RegistrationTest.register(RegistrationTest.java:26)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- register -->
</testsuite> <!-- Registration -->
